package dev.gkissel.forgeweave.data;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import org.junit.jupiter.api.Test;

/**
 * Parity audit T79 (issue #510): upstream {@code TinkerOredict} puts clear glass (+ its 16 dyed
 * variants), the seared brick item, every reusable gold cast and part pattern, and three of its part
 * types into Forge's old string oredict so other mods can hook into them. Forgeweave never picked
 * this up (docs/research/parity-audit-2026-08-18.md, T79) -- this pins the modern {@code c:}
 * convention-tag equivalent, generated by {@link ForgeweaveItemTagsProvider} /
 * {@link ForgeweaveBlockTagsProvider}. Plain filesystem scan of the generated tag JSON, same approach
 * as {@link ReinforcedPlateRecipeTest}.
 */
class ConventionTagsTest {

    private static Path projectRoot() {
        Path dir = Path.of("").toAbsolutePath();
        for (Path candidate = dir; candidate != null; candidate = candidate.getParent()) {
            if (Files.exists(candidate.resolve("settings.gradle"))) {
                return candidate;
            }
        }
        throw new AssertionError("could not locate project root (no settings.gradle found above " + dir + ")");
    }

    private static java.util.Set<String> values(String relativePath) throws IOException {
        Path json = projectRoot().resolve(relativePath);
        assertTrue(Files.isRegularFile(json), "expected generated tag JSON at " + json);
        JsonObject root = JsonParser.parseString(Files.readString(json, StandardCharsets.UTF_8)).getAsJsonObject();
        return StreamSupport.stream(root.getAsJsonArray("values").spliterator(), false)
                .map(JsonElement::getAsString)
                .collect(Collectors.toSet());
    }

    @Test
    void glassBlocksTagCoversClearGlassAndAllSixteenDyedVariants() throws IOException {
        var itemValues = values("src/generated/resources/data/c/tags/item/glass_blocks.json");
        var blockValues = values("src/generated/resources/data/c/tags/block/glass_blocks.json");

        assertTrue(itemValues.contains("forgeweave:clear_glass"), itemValues.toString());
        assertTrue(blockValues.contains("forgeweave:clear_glass"), blockValues.toString());
        for (String color : java.util.List.of("white", "orange", "magenta", "light_blue", "yellow", "lime", "pink",
                "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black")) {
            String id = "forgeweave:" + color + "_stained_clear_glass";
            assertTrue(itemValues.contains(id), "item glass_blocks missing " + id + ": " + itemValues);
            assertTrue(blockValues.contains(id), "block glass_blocks missing " + id + ": " + blockValues);
        }
    }

    @Test
    void dyedColorTagsCoverTheMatchingStainedClearGlass() throws IOException {
        var itemWhite = values("src/generated/resources/data/c/tags/item/dyed/white.json");
        var blockWhite = values("src/generated/resources/data/c/tags/block/dyed/white.json");
        assertTrue(itemWhite.contains("forgeweave:white_stained_clear_glass"), itemWhite.toString());
        assertTrue(blockWhite.contains("forgeweave:white_stained_clear_glass"), blockWhite.toString());

        var itemLightBlue = values("src/generated/resources/data/c/tags/item/dyed/light_blue.json");
        assertTrue(itemLightBlue.contains("forgeweave:light_blue_stained_clear_glass"), itemLightBlue.toString());
    }

    @Test
    void searedBrickJoinsTheIngotsConvention() throws IOException {
        var values = values("src/generated/resources/data/c/tags/item/ingots/seared_brick.json");
        assertTrue(values.contains("forgeweave:seared_brick"), values.toString());
    }

    @Test
    void castsTagAliasesTheExistingGoldCastsTag() throws IOException {
        var values = values("src/generated/resources/data/c/tags/item/casts.json");
        assertTrue(values.contains("#forgeweave:casts/gold"), values.toString());
    }

    @Test
    void patternsTagCoversTheBlankAndEveryShapePattern() throws IOException {
        var values = values("src/generated/resources/data/c/tags/item/patterns.json");
        assertTrue(values.contains("forgeweave:pattern_blank"), values.toString());
        assertTrue(values.contains("forgeweave:pattern_pickaxe_head"), values.toString());
        assertTrue(values.contains("forgeweave:pattern_katana_blade"), values.toString());
        assertTrue(values.contains("forgeweave:pattern_bow_limb"), values.toString());
        assertTrue(values.contains("forgeweave:pattern_sharpening_kit"), values.toString());
    }

    @Test
    void partsTagsCoverOnlyTheThreeUpstreamOredictedParts() throws IOException {
        var pickHead = values("src/generated/resources/data/c/tags/item/parts/pickaxe_head.json");
        var binding = values("src/generated/resources/data/c/tags/item/parts/tool_binding.json");
        var toolRod = values("src/generated/resources/data/c/tags/item/parts/tool_rod.json");

        assertTrue(pickHead.contains("forgeweave:pickaxe_head"), pickHead.toString());
        assertTrue(binding.contains("forgeweave:tool_binding"), binding.toString());
        assertTrue(toolRod.contains("forgeweave:tool_handle"), toolRod.toString());
    }
}
