package dev.gkissel.forgeweave.ponder;

import net.createmod.ponder.api.registration.PonderPlugin;
import net.createmod.ponder.api.registration.PonderSceneRegistrationHelper;
import net.createmod.ponder.foundation.PonderIndex;
import net.minecraft.resources.ResourceLocation;
import net.neoforged.fml.event.lifecycle.FMLClientSetupEvent;

import dev.gkissel.forgeweave.Forgeweave;
import dev.gkissel.forgeweave.item.ForgeweaveItems;

/**
 * Forgeweave's Ponder scenes (docs/SCOPE.md M2 issue #110 wired this seam; issue #664 -- a
 * maintainer-approved additive feature beyond 1.12 parity -- ships the first scene). Ponder
 * ({@code https://github.com/Creators-of-Create/Ponder}, {@code net.createmod.ponder}, MIT) is
 * jar-in-jar embedded together with its own required client dependency Flywheel (see build.gradle),
 * so every install has it; the {@code ModList} guard at this class's call site and the
 * {@link ForgeweavePonderHint} fallback stay for the residual case of a repackaged install
 * stripping the embedded jars.
 *
 * <p>Deliberately not {@code @EventBusSubscriber}-annotated: that annotation is scanned and the
 * class loaded on every install regardless of dist, which would touch {@code net.createmod.ponder}
 * API types (and so classload them) on a dedicated server, where {@code FMLClientSetupEvent} never
 * fires. Instead {@code Forgeweave}'s constructor registers {@link #onClientSetup} manually, after
 * confirming Ponder is on {@code ModList} -- see that call site's {@code // #110} comment.
 *
 * <p>Scenes register on an item's {@link ResourceLocation}; Ponder itself renders the hold-W
 * ("Ponder") affordance on that item's tooltip and plays the scene's storyboard against the
 * schematic at {@code assets/forgeweave/ponder/<path>.nbt}
 * (generated by {@code scripts/generate_ponder_schematics.py}). Scene text lives inline in the
 * storyboards ({@link ForgeweaveSmelteryScenes}) per Ponder's idiom and is extracted into lang keys
 * ({@code forgeweave.ponder.<scene>.*}) through {@code ForgeweaveLanguageProvider}, so every
 * player-facing string still flows through datagen.
 */
public final class ForgeweavePonderPlugin implements PonderPlugin {

    @Override
    public String getModId() {
        return Forgeweave.MODID;
    }

    @Override
    public void registerScenes(PonderSceneRegistrationHelper<ResourceLocation> helper) {
        // #664 -- the smeltery multiblock assembly, on the smeltery controller's item. Later
        // stations and structures are follow-up issues, one addStoryBoard line each.
        helper.addStoryBoard(ForgeweaveItems.STANDARD_CORE.getId(), "smeltery",
                ForgeweaveSmelteryScenes::assembly);
    }

    /**
     * {@link FMLClientSetupEvent} listener: plugins must be with {@code PonderIndex} before
     * Ponder's own {@code FMLLoadCompleteEvent} handler calls {@code PonderIndex.registerAll()};
     * client setup precedes load-complete, matching Ponder's documented registration idiom.
     */
    public static void onClientSetup(FMLClientSetupEvent event) {
        PonderIndex.addPlugin(new ForgeweavePonderPlugin());
    }
}
